# Generated by Django 3.1.7 on 2021-03-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=20, null=True)),
                ('discription', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
