# Generated by Django 3.1.7 on 2021-03-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20210324_0813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Board',
        ),
    ]
