# Generated by Django 3.1.7 on 2021-03-27 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyApp', '0008_auto_20210327_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='discription',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='MyApp.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='MyApp.board'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='lastUpdated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
