# Generated by Django 3.1.7 on 2021-04-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commnet',
            new_name='comment',
        ),
    ]
