# Generated by Django 3.1.7 on 2021-04-10 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_auto_20210405_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='MyApp.post'),
        ),
    ]
